## Data Cleaning

In [15]:
import pandas as pd 

benin = pd.read_csv('C:/Users/Suraphel/Desktop/Week-0/Optimal-Solar-Investment-Analysis/notebooks/benin.csv')
sierraleone = pd.read_csv('C:/Users/Suraphel/Desktop/Week-0/Optimal-Solar-Investment-Analysis/notebooks/sierraleone.csv')
togo = pd.read_csv('C:/Users/Suraphel/Desktop/Week-0/Optimal-Solar-Investment-Analysis/notebooks/togo.csv')

In [16]:
def clean_data(data):
    # replace -ve values with NaN for irradiance columns
    data[['GHI', 'DNI', 'DHI', 'ModA', 'ModB']] = data[['GHI', 'DNI', 'DHI', 'ModA', 'ModB']].applymap(lambda x: x if x >= 0 else pd.NA)

    # drop the 'comments' column 
    data.drop(columns=['Comments'],inplace=True)

    # fill missing values using forward (for time series) and backward (for any remaining NaNs)
    data.fillna(method='ffill', inplace=True) 
    data.fillna(method='bfill', inplace=True)

In [17]:
clean_data(benin)
benin.head()

C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data[['GHI', 'DNI', 'DHI', 'ModA', 'ModB']] = data[['GHI', 'DNI', 'DHI', 'ModA', 'ModB']].applymap(lambda x: x if x >= 0 else pd.NA)
C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)
C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill', inplace=True)
C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.fillna(method='bfill', inplace=True)

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB
0,2021-08-09 00:01,0.0,0.0,0.0,0.0,0.0,26.2,93.4,0.0,0.4,0.1,122.1,0.0,998,0,0.0,26.3,26.2
1,2021-08-09 00:02,0.0,0.0,0.0,0.0,0.0,26.2,93.6,0.0,0.0,0.0,0.0,0.0,998,0,0.0,26.3,26.2
2,2021-08-09 00:03,0.0,0.0,0.0,0.0,0.0,26.2,93.7,0.3,1.1,0.5,124.6,1.5,997,0,0.0,26.4,26.2
3,2021-08-09 00:04,0.0,0.0,0.0,0.0,0.0,26.2,93.3,0.2,0.7,0.4,120.3,1.3,997,0,0.0,26.4,26.3
4,2021-08-09 00:05,0.0,0.0,0.0,0.0,0.0,26.2,93.3,0.1,0.7,0.3,113.2,1.0,997,0,0.0,26.4,26.3

In [4]:
# clean data for sierraleone 
clean_data(sierraleone)
sierraleone.head()

C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data[['GHI', 'DNI', 'DHI', 'ModA', 'ModB']] = data[['GHI', 'DNI', 'DHI', 'ModA', 'ModB']].applymap(lambda x: x if x >= 0 else pd.NA)
C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)
C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill', inplace=True)
C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.fillna(method='bfill', inplace=True)

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB
0,2021-10-30 00:01,0.0,0.0,0.1,0.0,0.0,21.9,99.1,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6
1,2021-10-30 00:02,0.0,0.0,0.1,0.0,0.0,21.9,99.2,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6
2,2021-10-30 00:03,0.0,0.0,0.1,0.0,0.0,21.9,99.2,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6
3,2021-10-30 00:04,0.0,0.0,0.1,0.0,0.0,21.9,99.3,0.0,0.0,0.0,0.0,0.0,1002,0,0.1,22.3,22.6
4,2021-10-30 00:05,0.0,0.0,0.1,0.0,0.0,21.9,99.3,0.0,0.0,0.0,0.0,0.0,1002,0,0.0,22.3,22.6

In [5]:
# clean data for togo 
clean_data(togo)
togo.head()

C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data[['GHI', 'DNI', 'DHI', 'ModA', 'ModB']] = data[['GHI', 'DNI', 'DHI', 'ModA', 'ModB']].applymap(lambda x: x if x >= 0 else pd.NA)
C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)
C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill', inplace=True)
C:\Users\Suraphel\AppData\Local\Temp\ipykernel_4136\625447196.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.fillna(method='bfill', inplace=True)

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB
0,2021-10-25 00:01,0.0,0.0,0.0,0.0,0.0,24.8,94.5,0.9,1.1,0.4,227.6,1.1,977,0,0.0,24.7,24.4
1,2021-10-25 00:02,0.0,0.0,0.0,0.0,0.0,24.8,94.4,1.1,1.6,0.4,229.3,0.7,977,0,0.0,24.7,24.4
2,2021-10-25 00:03,0.0,0.0,0.0,0.0,0.0,24.8,94.4,1.2,1.4,0.3,228.5,2.9,977,0,0.0,24.7,24.4
3,2021-10-25 00:04,0.0,0.0,0.0,0.0,0.0,24.8,94.3,1.2,1.6,0.3,229.1,4.6,977,0,0.0,24.7,24.4
4,2021-10-25 00:05,0.0,0.0,0.0,0.0,0.0,24.8,94.0,1.3,1.6,0.4,227.5,1.6,977,0,0.0,24.7,24.4

## Conclusion

 The dataset was cleaned by addressing anomalies and handling missing values. Negative values in the 'GHI', 'DNI', and 'DHI' columns were replaced with NaN, and the entirely null 'Comments' column was removed. Missing values in the dataset were filled using forward and backward filling methods. The result is a cleaned dataset that is now ready for further analysis and modeling.